### ISSUE TITLE
Error from tracker when opening the entry offline

### ISSUE THREAD

**Issue by fellinir** [komikku-app/komikku#136]
### Steps to reproduce

1. Have a tracker set up in a manga
2. Be offline
3. Enter the entry from library

### Expected behavior

There is no error popup and I can enjoy it offline

### Actual behavior

A "no address associated with the name found" error from the tracker appears

### Komikku version

r9078

### Android version

Android 12

### Device

Lenovo tab m10 plus 3rd Gen (Qualcomm)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by fellinir** [comment]
Fixed it in r9149
